version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  jobs:
    create_environment:
      - "asdf plugin add uv"
      - "asdf install uv latest"
      - "asdf global uv latest"
      - "UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --group docs"
      - "UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv pip install ."
    install:  # skip this step; we already did it.
      - "true"

sphinx:
  configuration: "doc/source/conf.py"
  fail_on_warning: True
