name: "Unit test"


on:
  push:
    branches:
      - "main"
  pull_request:


jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Set up uv "
        uses: "astral-sh/setup-uv@v5"

      - name: "Run tests"
        run: "uv run nox -s test"
